use OJT;

--DDL 실습
-- 유저 테이블 생성
CREATE TABLE [dbo].[TB_USER](
	[IDX] [int] IDENTITY(1,1) NOT NULL,
	[USER_NM] [nvarchar](20) NULL,
	[USER_AGE] [numeric](10, 0) NULL,
	[USER_EMAIL] [nvarchar](50) NULL,
	[USER_SUBSCRIPTION_DATE] [nvarchar](8) NULL,
) ON [PRIMARY]

-- 유저 테이블에 등록자(식별자), 등록일자 추가
ALTER TABLE [dbo].[TB_USER] ADD REG_IDX INT, REG_DATE DATETIME

--유저 테이블 삭제
DROP TABLE [dbo].[TB_USER]


--DML 실습
--가입일자가 20230101부터  20230105 와 20230110 부터 20230115까지 조회한 후 UNION 실습
SELECT 
	IDX,
	USER_NM,
	USER_AGE,
	USER_EMAIL,
	USER_SUBSCRIPTION_DATE,
	REG_IDX,
	REG_DATE
FROM TB_USER
WHERE 1=1
AND USER_SUBSCRIPTION_DATE BETWEEN '20230101' AND '20230105'

UNION

SELECT 
	IDX,
	USER_NM,
	USER_AGE,
	USER_EMAIL,
	USER_SUBSCRIPTION_DATE,
	REG_IDX,
	REG_DATE
FROM TB_USER
WHERE 1=1
AND USER_SUBSCRIPTION_DATE BETWEEN '20230110' AND '20230115'

--DCL 실습
GRANT SELECT ON TB_USER TO select_user
REVOKE SELECT ON TB_USER FROM select_user
