USE [OJT]
GO

/****** Object:  Trigger [dbo].[USER_INSERT]    Script Date: 2023-02-05 오후 10:05:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER TRIGGER [dbo].[USER_INSERT]
ON [dbo].[TB_USER]
FOR UPDATE
AS

BEGIN
	
	DECLARE @IDX int,
			@USER_NM nvarchar(20),
			@USER_AGE numeric(10, 0),
			@USER_HEIGHT nvarchar(20),
			@USER_EMAIL nvarchar(50),
			@USER_SUBSCRIPTION_DATE nvarchar(8),
			@UPD_IDX int,
			@UPD_DATE datetime
	
	--수정자 또는 수정시간이 변경되었을 때 로그 생성하도록
	IF UPDATE(UPD_IDX) OR UPDATE(UPD_DATE)
	BEGIN
		SELECT
			@IDX = IDX,
			@USER_NM = USER_NM,
			@USER_AGE = USER_AGE,
			@USER_HEIGHT = USER_HEIGHT,
			@USER_EMAIL = USER_EMAIL,
			@USER_SUBSCRIPTION_DATE = USER_SUBSCRIPTION_DATE,
			@UPD_IDX = UPD_IDX,
			@UPD_DATE = UPD_DATE
		FROM INSERTED

		INSERT INTO TB_USER_LOG( USER_IDX, USER_NM, USER_AGE, USER_HEIGHT, USER_EMAIL, USER_SUBSCRIPTION_DATE, REG_IDX, REG_DATE)
		VALUES ( @IDX, @USER_NM, @USER_AGE, @USER_HEIGHT, @USER_EMAIL, @USER_SUBSCRIPTION_DATE, @UPD_IDX, @UPD_DATE )
	END
	

END
GO

ALTER TABLE [dbo].[TB_USER] ENABLE TRIGGER [USER_INSERT]
GO

